version: '3'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_DATABASE: 'mysql'
      MYSQL_PASSWORD: 'pass123'
      MYSQL_ROOT_PASSWORD: 'pass123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

volumes:
  postgres_data:
  mysql_data:
